apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  # Sterge automat aplicatiile child cand root-app este sters
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dannut/klist-infra
    targetRevision: staging
    # Urmăreste folderul argocd/ — orice Application adaugat aici
    # este detectat si aplicat automat de ArgoCD
    path: argocd
    plugin: 
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
