grafana:
  service:
    nodePort: 31002
    type: NodePort
  nodeSelector:
    kubernetes.io/hostname: master
prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: master
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
          storageClassName: longhorn
