apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  extraconfig-from-values.hcl: |-
    ui = true

    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }

    storage "file" {
      path = "/vault/data"
    }

    # --- Auto-Unseal block (Transit) ---
    seal "transit" {
      address            = "http://10.0.10.20:8205"
      key_name           = "autounseal-key"
      mount_path         = "transit/"
      tls_disable        = "true"
    }

    disable_mlock = true
