apiVersion: v1
kind: Secret
metadata:
  name: gcp-dr-cluster-secret
  namespace: argocd
  annotations:
    avp.kubernetes.io/vault-path: "kli/data/clusters/gcp-dr"
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: <path:kli/data/clusters/gcp-dr#name>
  server: <path:kli/data/clusters/gcp-dr#server>
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<path:kli/data/clusters/gcp-dr#caData>",
        "certData": "<path:kli/data/clusters/gcp-dr#certData>",
        "keyData": "<path:kli/data/clusters/gcp-dr#keyData>"
      }
    }
